### PR TITLE
Add support for osx-arm64

### PR DESCRIPTION
**Pull request by ghutchis**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ghutchis** [comment]
@conda-forge-admin, please rerender

**Comment by ghutchis** [comment]
Okay, I think this is ready to merge with a new `osx_arm64` build.

**Review by greglandrum — APPROVED** [review]
LGTM
Thanks Geoff!

**Comment by ghutchis** [comment]
I can't merge this @richardjgowers can this be merged? Thanks!

**Pull request merged**
