### PR TITLE
Add a Windows build script

### PR DESCRIPTION
**Pull request by ghutchis**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ghutchis** [comment]
@conda-forge-admin, please rerender

**Comment by ghutchis** [comment]
I don't have a good way to test the Windows build, but it builds at least.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by ghutchis** [comment]
I can't merge this @richardjgowers can this be merged? Thanks!

**Comment by greglandrum** [comment]
@richardjgowers : I could merge these, but I was waiting to see if you wanted to review/comment. If not I will go ahead and do the merge of this and #9

**Comment by richardjgowers** [comment]
Thanks @ghutchis !

**Comment by greglandrum** [comment]
@richardjgowers want me to resolve the conflicts?

**Comment by richardjgowers** [comment]
@greglandrum I'll have time today to do this, but if you're free then sure.  The diff is a little messy because of all the auto generated files

**Comment by ghutchis** [comment]
I can also close this and rebase - most of these are due to merging the `osx-arm64` build.

**Comment by richardjgowers** [comment]
@conda-forge-admin, please rerender

**Comment by richardjgowers** [comment]
@ghutchis I tried a messy merge and rerender, if that doesn't work then feel free to rebase onto a new branch

**Review by richardjgowers — APPROVED** [review]

**Comment by ghutchis** [comment]
Looks like it built, so 🤞 - I'll find a Windows user to test.

**Pull request merged**
